sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
before_script:
  - npm prune
after_success:
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
